databases:
  - name: mysitedb
    plan: pro-4gb
    databaseName: mysite
    user: mysite
    readReplicas:
      - name: my-db-replica-5
      - name: my-db-replica-1
      - name: my-db-replica-6
      - name: my-db-replica-2
      - name: my-db-replica-4
      - name: my-db-replica-3

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
